# Добавление нового клиента
POST http://localhost:3000/api/customers HTTP/1.1
Content-Type: application/json

{
  "name": "Иванов Иван",
  "email": "ivan@ivanov.local"
}

###

# Создание продукта
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "iphone 17",
  "price": 150000,
  "currency": "RUB",
  "stock": 15
}

###

# Создание заказа
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "customerId": "342d9844-4c68-49f3-bf31-12cc9a468cef",
  "items": [
    {
      "productId": "bd0bc0e0-778f-46ec-999d-9975dc96fbbc",
      "quantity": 1
    }
  ]
}

###
